import mongoose from 'mongoose';

const eventSchema = new mongoose.Schema(
  {
    camera: {
      type: mongoose.Schema.ObjectId,
      ref: 'Camera',
      required: true,
    },
    ruleTriggered: {
      type: mongoose.Schema.ObjectId,
      ref: 'Rule',
    },
    timestamp: {
      type: Date,
      default: Date.now,
    },
    aiSummary: {
      type: String,
      description: 'Human-readable summary generated by Gemini',
    },
    snapshotUrl: {
      type: String,
      description: 'URL or path to the saved snapshot frame',
    },
    confidence: {
      type: Number,
      min: 0,
      max: 1,
    },
    status: {
      type: String,
      enum: ['Pending', 'Approved', 'Dismissed', 'False Alarm'],
      default: 'Pending',
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model('Event', eventSchema);
